# Generated by Django 2.1.5 on 2019-05-12 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Краткое описание события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание события')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проведения')),
                ('status', models.CharField(choices=[('ACT', 'Активно'), ('INA', 'Неактивно')], default='ACT', max_length=3, verbose_name='Статус')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='events', to='groupapp.Group', verbose_name='Группа')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INT', 'Инициатор'), ('PRT', 'Участник')], max_length=3, verbose_name='Роль')),
                ('event', models.ForeignKey(on_delete='CASCADE', related_name='eventusers', to='eventapp.Event')),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='userevents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventuser',
            unique_together={('user', 'event')},
        ),
    ]
