# Generated by Django 2.1.5 on 2019-03-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='bvz gjkmpjdfntkz'),
        ),
    ]
