# Generated by Django 2.1.5 on 2019-03-29 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0002_group_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='username',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupsmodel', to=settings.AUTH_USER_MODEL),
        ),
    ]
