# Generated by Django 2.1.5 on 2019-04-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0002_auto_20190429_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(on_delete='PROTECT', to='groupapp.Category', verbose_name='Категория группы'),
        ),
    ]
