# Generated by Django 2.1.5 on 2019-03-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0005_group_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='username',
            new_name='user',
        ),
    ]
