# Generated by Django 2.1.5 on 2019-04-29 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0005_auto_20190429_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupapp.Category', verbose_name='Категория группы'),
        ),
    ]
