# Generated by Django 2.1.5 on 2019-04-29 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0006_auto_20190429_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='groupapp.Group'),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergroups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
