# Generated by Django 2.1.5 on 2019-05-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20190429_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Коментарий к покупке'),
        ),
    ]
