# Generated by Django 2.1.5 on 2019-03-27 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 13, 2, 15, 781268, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
    ]
