# Generated by Django 2.1.5 on 2019-04-03 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 7, 15, 13, 920273, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
    ]
