# Generated by Django 2.1.5 on 2019-04-15 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190415_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 17, 22, 52, 773556, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
    ]
