# Generated by Django 2.1.5 on 2019-03-27 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190327_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 14, 33, 24, 514011, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
    ]
