# Generated by Django 2.1.5 on 2019-04-17 09:09

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190417_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 9, 9, 5, 69571, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='contact_user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='Контакт пользователя'),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
