# Generated by Django 2.1.5 on 2019-04-29 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190429_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 9, 15, 54, 399706, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
    ]
