# Generated by Django 2.1.5 on 2019-03-27 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190327_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 14, 42, 25, 343898, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
    ]
