# Generated by Django 2.1.5 on 2019-04-15 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190415_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 17, 28, 49, 3644, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
    ]
