# Generated by Django 2.1.5 on 2019-03-29 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20190327_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 10, 32, 41, 167483, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
    ]
