# Generated by Django 2.1.5 on 2019-05-06 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20190429_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 5, 58, 33, 987184, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
    ]
