# Generated by Django 2.1.5 on 2019-05-08 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20190506_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 15, 25, 54, 720808, tzinfo=utc), editable=False, verbose_name='Activation key expires'),
        ),
    ]
