# Generated by Django 2.1.5 on 2019-04-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontactlist',
            name='contact_user',
        ),
        migrations.RemoveField(
            model_name='usercontactlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserContactList',
        ),
    ]
