# Generated by Django 2.1.5 on 2019-03-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingitem',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Коментарий к покупке'),
        ),
        migrations.AddField(
            model_name='shopingitem',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Покупка совершена'),
        ),
        migrations.AddField(
            model_name='shopingitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена покупки'),
        ),
    ]
